"""Generate a migration checklist from a blast radius.

Reporting the damage is half the job. The other half is telling a reviewer
exactly what to change, in dependency order, so the rename can actually ship.

The generated SQL is a starting point for a human to review, not something to
apply blind — DataHub knows a column is consumed, not the shape of every query
that consumes it. The artifact says so plainly.
"""

from __future__ import annotations

from .datahub_client import ColumnBlastRadius, LineageHit

# Downstream assets are fixed nearest-first: a view cannot be corrected before
# the table it selects from.
_ORDER = {"DATASET": 0, "DATA_JOB": 1, "DATA_FLOW": 1, "CHART": 2, "DASHBOARD": 3}


def _steps(radius: ColumnBlastRadius) -> list[LineageHit]:
    return sorted(radius.hits, key=lambda h: (h.degree, _ORDER.get(h.entity_type, 9)))


def generate_migration(
    radius: ColumnBlastRadius,
    old_column: str,
    new_column: str,
) -> str:
    """A reviewable, ordered migration plan in markdown."""
    lines: list[str] = []
    lines.append(f"# Migration plan: `{radius.dataset_name}.{old_column}` → `{new_column}`")
    lines.append("")
    lines.append(
        f"Generated by [Blast Radius](https://github.com/ritesh59697/datahub-blast-radius) "
        f"from DataHub lineage. **{len(radius.hits)} downstream entities** across "
        f"**{len(radius.platforms)} platforms** reference this column."
    )
    lines.append("")
    lines.append(
        "> Ordered nearest-first: each step assumes the ones above it have landed. "
        "The SQL below is a starting point for review — DataHub knows *that* a column "
        "is consumed, not the shape of every query consuming it. Read each change "
        "before applying it."
    )
    lines.append("")

    lines.append("## Backwards-compatible rollout (recommended)")
    lines.append("")
    lines.append(
        "Renaming in place breaks every consumer at once. Shipping the alias first "
        "lets consumers migrate independently:"
    )
    lines.append("")
    lines.append("```sql")
    lines.append(f"-- Step 1: expose both names from {radius.dataset_name}")
    lines.append("select")
    lines.append(f"    {old_column} as {new_column},")
    lines.append(f"    {old_column},  -- deprecated: remove after consumers migrate")
    lines.append("    ...")
    lines.append(f"from {{{{ ref('{radius.dataset_name}') }}}}")
    lines.append("```")
    lines.append("")
    lines.append(
        f"Then work through the consumers below, and drop `{old_column}` in a "
        f"follow-up PR once none remain."
    )
    lines.append("")

    lines.append("## Consumers to update")
    lines.append("")

    grouped: dict[str, list[LineageHit]] = {}
    for hit in _steps(radius):
        grouped.setdefault(hit.platform, []).append(hit)

    step = 1
    for platform, hits in sorted(grouped.items(), key=lambda kv: min(h.degree for h in kv[1])):
        lines.append(f"### {platform}")
        lines.append("")
        for hit in hits:
            owners = radius.downstream_owners.get(hit.urn, [])
            who = f" — owner: {', '.join(o.label for o in owners[:2])}" if owners else ""
            label = hit.entity_type.replace("_", " ").title()
            hops = f"{hit.degree} hop{'s' if hit.degree != 1 else ''}"
            lines.append(f"{step}. **{hit.name}** ({label}, {hops}){who}")
            if hit.entity_type == "DATASET":
                lines.append(f"   - update any `select` referencing `{old_column}`")
            elif hit.entity_type == "CHART":
                lines.append(f"   - repoint the field binding to `{new_column}`")
            elif hit.entity_type == "DASHBOARD":
                lines.append("   - verify tiles render after the upstream charts are fixed")
            elif hit.entity_type in ("DATA_JOB", "DATA_FLOW"):
                lines.append("   - check the job's column mapping and re-run a backfill if needed")
            step += 1
        lines.append("")

    if radius.notify:
        lines.append("## Notify")
        lines.append("")
        for owner, affected in radius.notify[:8]:
            contact = f" (`{owner.email}`)" if owner.email else ""
            lines.append(f"- **{owner.label}**{contact} — {len(affected)} affected asset(s)")
        lines.append("")

    lines.append("## Verification")
    lines.append("")
    lines.append("```bash")
    lines.append("# Re-run the analysis; it should report no remaining consumers")
    lines.append(f"blast-radius analyze --column {radius.dataset_name}.{old_column}")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)
